<?php

namespace AppBundle\Repository;

/**
 * ObjetsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ObjetsRepository extends \Doctrine\ORM\EntityRepository
{
}
