<?php

namespace AppBundle\Repository;

/**
 * professional_statusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class professional_statusRepository extends \Doctrine\ORM\EntityRepository
{
}
